name: shall
favicon: null
layout_spectrum: 0.33018669323064387
typography_spectrum: 0.4387997449375689
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.6007018857635558
  lightness: 0.6109863135498017
  saturation: 0.0836856837850064
  rhythmicContrast: 0.9040549856144935
purpose: []
